name: Build Flet APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Dependencies
        run: |
          pip install flet
          
      - name: Build APK
        run: |
          # FLET_NO_INPUT ile etkileşimi tamamen kapatıyoruz
          # --name ve --project-id ile yapılandırmayı otomatikleştiriyoruz
          flet build apk --product-name "HesapMakinem" --project-id "com.ahmet.hesapmakinesi"
        env:
          FLET_NO_INPUT: "true"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: hesap-makinesi-apk
          path: build/apk/app-release.apk
